//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExandasPostgres.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExandasPostgres.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B16x16_Cut {
            get {
                object obj = ResourceManager.GetObject("B16x16_Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B16x16_Edit {
            get {
                object obj = ResourceManager.GetObject("B16x16_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B16x16_Folder_Inbox {
            get {
                object obj = ResourceManager.GetObject("B16x16_Folder_Inbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap catchuprelease_rls {
            get {
                object obj = ResourceManager.GetObject("catchuprelease_rls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f6016_001 {
            get {
                object obj = ResourceManager.GetObject("f6016_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HAIwpqi8JERUhCXqeXocwW6xy2ZyRlzmEHUig9dzactiQMtSMAkYDfErp43ZBoIA2bpXMwqslVeCaNK4
        ///yAJ34v4EurI140mw0SVagvURwdDOygRXOUro15Z7qoNi5zJm7uAmvedxXyctAeh62rm8M4qB3ZWdqZQx
        ///eI0QhxTz0qzzzNy9JWf6fGN4isJEjmgEScJCAEmu9tDLJ1qd93oWmvyyzl2NhRIysPihYbm10UGY0bER
        ///edoSXbwFMuwyvtizX1RqoQr0C3v4UNoNvaU7m6D6HGN9MbucpImqiksM98tLo7YYJBQoj9iRxqzg5ECM
        ///YeHPPSJRkPaECglWZOe3gyVwiCGlPtJ56FWR6o3h5fuDuBxat54gVtUJnCNeIx5pq1Ro6RhWb9iwcgRr
        ///DVMIGm2217I2hHk2xoFLgrdoaw0ok2TF3QNB5nj7LyZCCOW4P6wqkn93hUdzCjkNrmCRUTt4s511pcuF
        ///mXpyhKQ61cTeAvDg2KOe [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string IDIOMATIC {
            get {
                return ResourceManager.GetString("IDIOMATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TABLE;OWNER
        ///TABLE;TABLESPACE_NAME
        ///TABLE;PERSISTENCE
        ///TABLE;ACCESS_METHOD
        ///TABLE;IS_PARTITIONED
        ///TABLE;IS_PARTITION
        ///TABLE;HAS_SUBCLASS
        ///TABLE;ROW_SECURITY
        ///TABLE;FORCE_ROW_SECURITY
        ///TABLE;DESCRIPTION
        ///TABLE;ACCESS_PRIVILEGES
        ///TABLE;OPTIONS
        ///TABLE;PARTITION_KEY
        ///TABLE;PARTITION_BOUND
        ///TABLE COLUMN;COLUMN_NUM
        ///TABLE COLUMN;DATA_TYPE
        ///TABLE COLUMN;COLLATION
        ///TABLE COLUMN;NULLABLE
        ///TABLE COLUMN;DATA_DEFAULT
        ///TABLE COLUMN;IDENTITY
        ///TABLE COLUMN;GENERATED
        ///TABLE COLUMN;STORAGE
        ///TABLE COLUMN;COMPRESSION
        ///TABLE C [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string REFERENCES {
            get {
                return ResourceManager.GetString("REFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon sextant {
            get {
                object obj = ResourceManager.GetObject("sextant", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
