//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExandasPostgres.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExandasPostgres.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About {0}.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;About....
        /// </summary>
        internal static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activate the addition of a record.
        /// </summary>
        internal static string ActivateAddition {
            get {
                return ResourceManager.GetString("ActivateAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The application will be restarted to be taken into account..
        /// </summary>
        internal static string ApplicationRestarted {
            get {
                return ResourceManager.GetString("ApplicationRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete the following record :.
        /// </summary>
        internal static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At least one schema mapping required.
        /// </summary>
        internal static string AtLeastOneSchemaMappingRequired {
            get {
                return ResourceManager.GetString("AtLeastOneSchemaMappingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot delete this record because it occurs in at least one comparison set..
        /// </summary>
        internal static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checking the connection.
        /// </summary>
        internal static string CheckingTheConnection {
            get {
                return ResourceManager.GetString("CheckingTheConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à check constraints.
        /// </summary>
        internal static string Checks {
            get {
                return ResourceManager.GetString("Checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compact.
        /// </summary>
        internal static string Compact {
            get {
                return ResourceManager.GetString("Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compaction completed.
        /// </summary>
        internal static string CompactionCompleted {
            get {
                return ResourceManager.GetString("CompactionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compact the local database.
        /// </summary>
        internal static string CompactLocalDatabase {
            get {
                return ResourceManager.GetString("CompactLocalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Compact the local database.
        /// </summary>
        internal static string CompactLocalDatabaseMenu {
            get {
                return ResourceManager.GetString("CompactLocalDatabaseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison report.
        /// </summary>
        internal static string ComparisonReport {
            get {
                return ResourceManager.GetString("ComparisonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison set detail.
        /// </summary>
        internal static string ComparisonSetDetail {
            get {
                return ResourceManager.GetString("ComparisonSetDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison set ID.
        /// </summary>
        internal static string ComparisonSetID {
            get {
                return ResourceManager.GetString("ComparisonSetID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of comparison sets.
        /// </summary>
        internal static string ComparisonSetList {
            get {
                return ResourceManager.GetString("ComparisonSetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison set name.
        /// </summary>
        internal static string ComparisonSetName {
            get {
                return ResourceManager.GetString("ComparisonSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison set name required.
        /// </summary>
        internal static string ComparisonSetNameRequired {
            get {
                return ResourceManager.GetString("ComparisonSetNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison sets.
        /// </summary>
        internal static string ComparisonSets {
            get {
                return ResourceManager.GetString("ComparisonSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection failed..
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection ID.
        /// </summary>
        internal static string ConnectionID {
            get {
                return ResourceManager.GetString("ConnectionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection name.
        /// </summary>
        internal static string ConnectionName {
            get {
                return ResourceManager.GetString("ConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection name required.
        /// </summary>
        internal static string ConnectionNameRequired {
            get {
                return ResourceManager.GetString("ConnectionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C&amp;onnections and comparison sets.
        /// </summary>
        internal static string ConnectionsComparisonSets {
            get {
                return ResourceManager.GetString("ConnectionsComparisonSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database required.
        /// </summary>
        internal static string DatabaseRequired {
            get {
                return ResourceManager.GetString("DatabaseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete record ?.
        /// </summary>
        internal static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delta of {0}.
        /// </summary>
        internal static string DeltaOf {
            get {
                return ResourceManager.GetString("DeltaOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à domains.
        /// </summary>
        internal static string Domains {
            get {
                return ResourceManager.GetString("Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you confirm the generation of the comparison report ?.
        /// </summary>
        internal static string DoYouConfirmGeneration {
            get {
                return ResourceManager.GetString("DoYouConfirmGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entity.
        /// </summary>
        internal static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ExandasPostgres Error.
        /// </summary>
        internal static string ExandasPostgresError {
            get {
                return ResourceManager.GetString("ExandasPostgresError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à exclusion constraints.
        /// </summary>
        internal static string Exclusions {
            get {
                return ResourceManager.GetString("Exclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export connections and comparison sets.
        /// </summary>
        internal static string ExportConnectionsComparisonSets {
            get {
                return ResourceManager.GetString("ExportConnectionsComparisonSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Export.
        /// </summary>
        internal static string ExportMenu {
            get {
                return ResourceManager.GetString("ExportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export performed in the file :.
        /// </summary>
        internal static string ExportPerformed {
            get {
                return ResourceManager.GetString("ExportPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à extensions.
        /// </summary>
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File size :.
        /// </summary>
        internal static string FileSizeColon {
            get {
                return ResourceManager.GetString("FileSizeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter settings.
        /// </summary>
        internal static string FilterSettings {
            get {
                return ResourceManager.GetString("FilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à foreign keys.
        /// </summary>
        internal static string ForeignKeys {
            get {
                return ResourceManager.GetString("ForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à foreign table columns.
        /// </summary>
        internal static string ForeignTableColumns {
            get {
                return ResourceManager.GetString("ForeignTableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à foreign tables.
        /// </summary>
        internal static string ForeignTables {
            get {
                return ResourceManager.GetString("ForeignTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Form data validation error..
        /// </summary>
        internal static string FormError {
            get {
                return ResourceManager.GetString("FormError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à for PostgreSQL.
        /// </summary>
        internal static string ForPostgres {
            get {
                return ResourceManager.GetString("ForPostgres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à functions.
        /// </summary>
        internal static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate the comparison report.
        /// </summary>
        internal static string GenerateComparisonReport {
            get {
                return ResourceManager.GetString("GenerateComparisonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparison report generation in progress....
        /// </summary>
        internal static string GenerationInProgress {
            get {
                return ResourceManager.GetString("GenerationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Host.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Host name.
        /// </summary>
        internal static string Hostname {
            get {
                return ResourceManager.GetString("Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hostname required.
        /// </summary>
        internal static string HostnameRequired {
            get {
                return ResourceManager.GetString("HostnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import connections and comparison sets from a file.
        /// </summary>
        internal static string ImportConnectionsComparisonSets {
            get {
                return ResourceManager.GetString("ImportConnectionsComparisonSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Import.
        /// </summary>
        internal static string ImportMenu {
            get {
                return ResourceManager.GetString("ImportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import of connections and comparison sets performed..
        /// </summary>
        internal static string ImportPerformed {
            get {
                return ResourceManager.GetString("ImportPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à index columns.
        /// </summary>
        internal static string IndexColumns {
            get {
                return ResourceManager.GetString("IndexColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à indexes.
        /// </summary>
        internal static string Indexes {
            get {
                return ResourceManager.GetString("Indexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Label.
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last comparison report.
        /// </summary>
        internal static string LastComparisonReport {
            get {
                return ResourceManager.GetString("LastComparisonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last report time.
        /// </summary>
        internal static string LastReportTime {
            get {
                return ResourceManager.GetString("LastReportTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch of the comparison report ?.
        /// </summary>
        internal static string LaunchComparisonReport {
            get {
                return ResourceManager.GetString("LaunchComparisonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of schema mappings.
        /// </summary>
        internal static string ListSchemaMappings {
            get {
                return ResourceManager.GetString("ListSchemaMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading {1} {0}.
        /// </summary>
        internal static string LoadingObjects {
            get {
                return ResourceManager.GetString("LoadingObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local database.
        /// </summary>
        internal static string LocalDatabase {
            get {
                return ResourceManager.GetString("LocalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local database backup.
        /// </summary>
        internal static string LocalDatabaseBackup {
            get {
                return ResourceManager.GetString("LocalDatabaseBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local database :.
        /// </summary>
        internal static string LocalDatabaseColon {
            get {
                return ResourceManager.GetString("LocalDatabaseColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Local database size.
        /// </summary>
        internal static string LocalDatabaseSize {
            get {
                return ResourceManager.GetString("LocalDatabaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à materialized view columns.
        /// </summary>
        internal static string MaterializedViewColumns {
            get {
                return ResourceManager.GetString("MaterializedViewColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à materialized views.
        /// </summary>
        internal static string MaterializedViews {
            get {
                return ResourceManager.GetString("MaterializedViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify.
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;Not specified&gt;.
        /// </summary>
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object in source absent in target.
        /// </summary>
        internal static string ObjectInSource {
            get {
                return ResourceManager.GetString("ObjectInSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object in target absent in source.
        /// </summary>
        internal static string ObjectInTarget {
            get {
                return ResourceManager.GetString("ObjectInTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object name.
        /// </summary>
        internal static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation canceled..
        /// </summary>
        internal static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parent object.
        /// </summary>
        internal static string ParentObject {
            get {
                return ResourceManager.GetString("ParentObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password required.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please check that the document is not already open in Excel..
        /// </summary>
        internal static string PleaseCheckExcel {
            get {
                return ResourceManager.GetString("PleaseCheckExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port required.
        /// </summary>
        internal static string PortRequired {
            get {
                return ResourceManager.GetString("PortRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à primary keys.
        /// </summary>
        internal static string PrimaryKeys {
            get {
                return ResourceManager.GetString("PrimaryKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Property.
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Property difference.
        /// </summary>
        internal static string PropertyDifference {
            get {
                return ResourceManager.GetString("PropertyDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Property name required in this context.
        /// </summary>
        internal static string PropertyNameRequired {
            get {
                return ResourceManager.GetString("PropertyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purge comparison reports.
        /// </summary>
        internal static string PurgeComparisonReports {
            get {
                return ResourceManager.GetString("PurgeComparisonReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purging comparison reports.
        /// </summary>
        internal static string PurgingComparisonReports {
            get {
                return ResourceManager.GetString("PurgingComparisonReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purging metadata tables.
        /// </summary>
        internal static string PurgingMetadata {
            get {
                return ResourceManager.GetString("PurgingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restoring the local database.
        /// </summary>
        internal static string RestoringLocalDatabase {
            get {
                return ResourceManager.GetString("RestoringLocalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save the filter settings applicable to the comparison set here to exclude matching rows in the comparison report..
        /// </summary>
        internal static string SaveTheFilterSettings {
            get {
                return ResourceManager.GetString("SaveTheFilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Schema [{0}] does not exist in the source database [{1}].
        /// </summary>
        internal static string SchemaDoesNotExistSource {
            get {
                return ResourceManager.GetString("SchemaDoesNotExistSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Schema [{0}] does not exist in the target database [{1}].
        /// </summary>
        internal static string SchemaDoesNotExistTarget {
            get {
                return ResourceManager.GetString("SchemaDoesNotExistTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Schema mapping.
        /// </summary>
        internal static string SchemaMapping {
            get {
                return ResourceManager.GetString("SchemaMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Schema mapping detail.
        /// </summary>
        internal static string SchemaMappingDetail {
            get {
                return ResourceManager.GetString("SchemaMappingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Schema mapping ID.
        /// </summary>
        internal static string SchemaMappingID {
            get {
                return ResourceManager.GetString("SchemaMappingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sequences.
        /// </summary>
        internal static string Sequences {
            get {
                return ResourceManager.GetString("Sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server connection detail.
        /// </summary>
        internal static string ServerConnectionDetail {
            get {
                return ResourceManager.GetString("ServerConnectionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server connections.
        /// </summary>
        internal static string ServerConnections {
            get {
                return ResourceManager.GetString("ServerConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of server connections.
        /// </summary>
        internal static string ServerConnectionsList {
            get {
                return ResourceManager.GetString("ServerConnectionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source connection.
        /// </summary>
        internal static string SourceConnection {
            get {
                return ResourceManager.GetString("SourceConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source database.
        /// </summary>
        internal static string SourceDatabase {
            get {
                return ResourceManager.GetString("SourceDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source schema.
        /// </summary>
        internal static string SourceSchema {
            get {
                return ResourceManager.GetString("SourceSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source schema required.
        /// </summary>
        internal static string SourceSchemaRequired {
            get {
                return ResourceManager.GetString("SourceSchemaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source server connection.
        /// </summary>
        internal static string SourceServerConnection {
            get {
                return ResourceManager.GetString("SourceServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source server connection required.
        /// </summary>
        internal static string SourceServerConnectionRequired {
            get {
                return ResourceManager.GetString("SourceServerConnectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source value.
        /// </summary>
        internal static string SourceValue {
            get {
                return ResourceManager.GetString("SourceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à extended statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successful connection.
        /// </summary>
        internal static string SuccessfulConnection {
            get {
                return ResourceManager.GetString("SuccessfulConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à table columns.
        /// </summary>
        internal static string TableColumns {
            get {
                return ResourceManager.GetString("TableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à tables.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à target.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target connection.
        /// </summary>
        internal static string TargetConnection {
            get {
                return ResourceManager.GetString("TargetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target database.
        /// </summary>
        internal static string TargetDatabase {
            get {
                return ResourceManager.GetString("TargetDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target schema.
        /// </summary>
        internal static string TargetSchema {
            get {
                return ResourceManager.GetString("TargetSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target schema required.
        /// </summary>
        internal static string TargetSchemaRequired {
            get {
                return ResourceManager.GetString("TargetSchemaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target server connection.
        /// </summary>
        internal static string TargetServerConnection {
            get {
                return ResourceManager.GetString("TargetServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target server connection required.
        /// </summary>
        internal static string TargetServerConnectionRequired {
            get {
                return ResourceManager.GetString("TargetServerConnectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target value.
        /// </summary>
        internal static string TargetValue {
            get {
                return ResourceManager.GetString("TargetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à triggers.
        /// </summary>
        internal static string Triggers {
            get {
                return ResourceManager.GetString("Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TRUNCATED.
        /// </summary>
        internal static string Truncated {
            get {
                return ResourceManager.GetString("Truncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à types.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to delete last schema mapping..
        /// </summary>
        internal static string UnableToDeleteLastSchemaMapping {
            get {
                return ResourceManager.GetString("UnableToDeleteLastSchemaMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à uniques.
        /// </summary>
        internal static string Uniques {
            get {
                return ResourceManager.GetString("Uniques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User name required.
        /// </summary>
        internal static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à view columns.
        /// </summary>
        internal static string ViewColumns {
            get {
                return ResourceManager.GetString("ViewColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View the comparison report.
        /// </summary>
        internal static string ViewComparisonReport {
            get {
                return ResourceManager.GetString("ViewComparisonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à views.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
